apiVersion: v1
kind: PersistentVolume
metadata:
  name: podman-images
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 50Gi
  #hostPath:
  #  path: /home/smikhtoniuk/Work/projects/kamu/odds/odds-demo/podman-images
